### ISSUE TITLE
About how the exam is conducted

### ISSUE THREAD

**Issue by hoosong0235** [kaist-cp/cs220#142] opened 2022-10-18 06:49 UTC
Hello professor. It's a sensitive issue, and I don't know if it's something I can express my opinion on as a student, but I'm posting it carefully. I think you know that some problems occurred during the second part of this midterm exam.

Of course, testing with the Rust Playground and the std library has the advantage of not being able to get help from rust-analyzer and preventing cheating.

However, as those who have taken this midterm exam in person, I think there will be many students who have not been able to show their ability as much as they have studied due to technical inconvenience.

The Rust Playground is very different from the IDE environment that we actually practiced through assignments and will develop in the future. The downside is that we have to copy-paste all the assert! macro into the main function that is created by myself.

I used the assert! macro that is written in comment to validate my code, by copying and pasting each assert! macro one by one, and this process took a lot of time. Of course, other students may have taken this time too, but I think it is more important to create an environment where all students can focus solely on solving the exam questions.

From the next exam, instead of Rust Playground, how about uploading a problem file like we did with the assignments and submitting it after solving the problem through the IDE or ssh? I know this is forward suggestion, but I would really appreciate it if you consider it just as a student's opinion. Thank you.

**Comment by buttercrab** [comment] 2022-10-18 10:03
BTW you can press `cmd(ctrl) + /` to uncomment/comment (toggle) a selection. I assume this feature is possible in replit, too.

**Comment by Lee-Janggun** [comment] 2022-10-19 05:51
* An option may be to provide a playground-link that is pre-filled. E.g, if the task is to print hello world, one will be given the following link
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=8a9ad6fc2541d36b816b265a70b6599d

* Another option may be to use GitHub Classroom, and allow students to use VsCode Dev to modify it online.

**Comment by jeehoonkang** [comment] 2022-12-13 09:27
Closing, as I believe the issue is addressed in the final exam.

**Closed by jeehoonkang** 2022-12-13 09:27 UTC
Labels: enhancement
